title: TechSnazzy Blog

description: >- # this means to ignore newlines until "baseurl:"
  I'm Sean and TechSnazzy is my technology consultation services business. I specialize in Windows, macOS, Linux, networking, cloud, mobile, security and more. This is my blog to share my experiences. Enjoy!

# Local
# baseurl: ""
# url: ""

# GitHub
baseurl: "sean-blog"
url: "https://techsnazzy.com"

twitter_username: seanmorrison
github_username:  techsnazzy
linkedin_username: theseanmorrison

# Build settings
theme: minima
plugins:
  - jekyll-feed

show_excerpts: true

# social_links:
#    - { platform: facebook,       user_url: "https://www.facebook.com/seanmorrison" }
#    - { platform: github,         user_url: "https://github.com/TechSnazzy" }
#    - { platform: instagram,      user_url: "https://www.instagram.com/seanpostingthings" }
#    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/theseanmorrison" }
#    - { platform: twitter,        user_url: "https://twitter.com/seanmorrison" }
#    - { platform: youtube,        user_url: "https://www.youtube.com/@TechSnazzyMedia" }